### ISSUE TITLE
booster-um doesn't run when installed, upgraded or removed

### ISSUE THREAD

**Issue by ishanarora** [Zile995/booster-um#15]
Ideally the alpm hooks should also trigger when booster-um is installed, upgraded or removed.

We could include the following path targets in install hook:
- `usr/bin/booster-um`
- `usr/share/booster-um/*`
- `usr/share/libalpm/scripts/booster-um-install`

We could also include `usr/bin/booster-um` in the remove hook.

**Comment by Zile995** [comment]
Hi, thank you for creating the issue.

`usr/bin/booster-um` should be enough, because it will be installed with each package update/upgrade and it will trigger the UKI regeneration. I will include it, thanks.

Adding it to the `remove` hook is not ideal, because this hook removes non-existent kernels. Remove hook is also the `post-transaction hook`, because when upgrading the kernel, the EFI entry would first be deleted and then added. That would mess up the boot order.

If you know a way to save the EFI boot order on upgrade alpm operation, I would be grateful.

**Comment by ishanarora** [comment]
I didn't realise the remove hook was `PostTransaction`. A `PreTransaction` hook would make more sense because a kernel and booster-um could both be uninstalled in the same transaction. Sorry, I do not have a solution for the boot order issue.

**Comment by Zile995** [comment]
That's right, I didn't think about deleting the booster-um.

Ok, I have an idea.
We can simply save the boot order number in the tmpfile when the kernel is updated, and restore it later.
